### ISSUE TITLE
minicdn

### ISSUE THREAD

**Issue by gexinworks** [codeskyblue/gosuv#67]
@codeskyblue ,你好，我在studygolang上面看到了minicdn的介绍，对这个项目很感兴趣，可是貌似仓库被删除了，是迁移了项目地址还是因为其他原因呢？可以给个新的项目地址或者发一份源码给我吗？邮箱wjzhangcsu@126.com

**Comment by codeskyblue** [comment]
已经停止维护了

    
        
            
                
                    
                        
                    
                    
                        
                            命令行
                            
                            
                                
                                    邮箱：codeskyblue@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
在2018年07月14日 16:44，Works 写道： 你好，我在studygolang上面看到了minicdn的介绍，对这个项目很感兴趣，可是貌似仓库被删除了，是迁移了项目地址还是因为其他原因呢？可以给个新的项目地址或者发一份源码给我吗？邮箱wjzhangcsu@126.com

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codeskyblue/gosuv","title":"codeskyblue/gosuv","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/codeskyblue/gosuv"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"minicdn (#67)"}],"action":{"name":"View Issue","url":"https://github.com/codeskyblue/gosuv/issues/67"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/codeskyblue/gosuv/issues/67",
"url": "https://github.com/codeskyblue/gosuv/issues/67",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "minicdn (#67)",
"sections": [
{
"text": "",
"activityTitle": "**Works**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@wjzhangcsu",
"facts": [
{
"name": "Repository: ",
"value": "codeskyblue/gosuv"
},
{
"name": "Issue #: ",
"value": 67
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"codeskyblue/gosuv\",\n\"issueId\": 67,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"codeskyblue/gosuv\",\n\"issueId\": 67\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/codeskyblue/gosuv/issues/67"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356459021\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by gexinworks** [comment]
可以发一份代码给我吗？


| |
电气信息1112班张文杰
邮箱：wjzhangcsu@126.com
|

签名由 网易邮箱大师 定制

On 07/14/2018 17:47, shengxiang wrote:

已经停止维护了










命令行



邮箱：codeskyblue@gmail.com







签名由 网易邮箱大师 定制
在2018年07月14日 16:44，Works 写道： 你好，我在studygolang上面看到了minicdn的介绍，对这个项目很感兴趣，可是貌似仓库被删除了，是迁移了项目地址还是因为其他原因呢？可以给个新的项目地址或者发一份源码给我吗？邮箱wjzhangcsu@126.com

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codeskyblue/gosuv","title":"codeskyblue/gosuv","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/codeskyblue/gosuv"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"minicdn (#67)"}],"action":{"name":"View Issue","url":"https://github.com/codeskyblue/gosuv/issues/67"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/codeskyblue/gosuv/issues/67",
"url": "https://github.com/codeskyblue/gosuv/issues/67",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "minicdn (#67)",
"sections": [
{
"text": "",
"activityTitle": "**Works**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@wjzhangcsu",
"facts": [
{
"name": "Repository: ",
"value": "codeskyblue/gosuv"
},
{
"name": "Issue #: ",
"value": 67
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"codeskyblue/gosuv\",\n\"issueId\": 67,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"codeskyblue/gosuv\",\n\"issueId\": 67\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/codeskyblue/gosuv/issues/67"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356459021\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by codeskyblue** [comment]
代码太乱了，不想开源出去，请不要再要了
